evaluate/Professional_evaluation.md
evaluate/README.md

* Update README.md
* Update Professional_evaluation.md

[DOC] Update docs in evaluate folder

---

scripts/qa_generation/config/config.py
scripts/qa_generation/main.py

Add concurrent functions for QA generation

Add concurrent functions (#1)

---

README.md
README_EN.md

Update for new concurrency feature

[DOC] Update README

---

LICENSE
datasets/README.md
datasets/README_EN.md

* Update README.md
* Update README_EN.md
* Update License

[DOC] Update README.md in datasets

---

scripts/qa_generation/main.py
scripts/qa_generation/util/data_loader.py

Each thread stores the generated content independently, and finally integrates the generated content into a file

Update multi QA generation process

---

README.md
README_EN.md
evaluate/Professional_evaluation.md
evaluate/Professional_evaluation_EN.md
evaluate/README.md

* Update EmoLLM V2.0’s evaluation score
* Update README.md/README_EN.md
* Fix some bugs in docs

[DOC] Update EmoLLM V2.0’s evaluation details and fix some bugs in docs

---

README.md

update personal info and small format optimizations

update personal info and small format optimizations

---

README_EN.md

update personal info and translations for contents in a table

update personal info and translations for contents in a table

---

README_EN.md

Update README_EN.md with xlab demo links

---

generate_data/qwen_gen_data_NoBash.py

Update qwen_gen_data_NoBash.py 添加对qwen-max的异常处理

---

README.md
README_EN.md

update README.md and README_EN.md

update README.md and README_EN.md

---

datasets/deduplicate.py

添加针对合并后json文件在conversation维度的去重功能

add deduplicate.py

---

README.md
README_EN.md

scientist.json

---

README.md
README_EN.md

Reverts SmartFlowAI/EmoLLM#146

Revert "readme"

---

xtuner_config/internlm2_7b_chat_qlora_e3_mother.py

internlm2_7b_chat_qlora_e3_mother.py，基于 Scientist 微调脚本改写。

多轮对话母亲角色的微调脚本

---

README.md
README_EN.md

中文版 readme：增加王几行XING、思在的作者信息
英文版 readme：增加王几行XING、思在的作者信息；2024.4.2 母亲角色多轮对话在 hf 的上传

中英文版本 readme 的更新

---

README_EN.md

[Doc] Update README_EN.md

---

README.md
README_EN.md
xtuner_config/README_internlm2_7b_base_qlora.md

InternLM2-Base-7B QLoRA微调模型 链接和测评结果更新

InternLM2-Base-7B QLoRA微调模型 链接和测评结果更新

---

README.md
README_EN.md

update model config file links

update model config file links

---

README.md
README_EN.md

Reverts SmartFlowAI/EmoLLM#188

Revert "update model config file links"

---

app.py

Fix the bug that openxlab platform cannot be deployed.

Fix the bug that openxlab platform cannot be deployed.

---

README.md
README_EN.md
app.py
download_model.py

Additional, remove hard code with a variable in [**update download_model**](https://github.com/SmartFlowAI/EmoLLM/commit/5d0f60478b7b16d6087e8ea8deba16b94a99fbb5)

update model table in main readme and download_model.py

---

app.py

2024-04-22 13:19:55.349 Port 7860 is already in use

update port num

---

README.md
README_EN.md
xtuner_config/pt/README.md
xtuner_config/pt/ft2pt.py
xtuner_config/pt/internlm2_chat_1_8b_qlora_e3_pt.py

add Incremental Pre-training Guide

---

README.md
README_EN.md
datasets/README.md
datasets/README_EN.md

* add new dataset - multi_turn_dataset_3
* dataset `multi_turn_dataset_3` from [SoulChat](https://github.com/scutcyr/SoulChat)

[DOC] Update new dataset

---

README.md
README_EN.md
web_internlm2_5.py

webV3  opt
